apiVersion: v1
kind: Service
metadata:
  name: vh-brain-service
  namespace: virtual-human
spec:
  selector:
    app: vh-brain
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32000
  type: NodePort
